<?php

// require_once('../config.php');

// $db_user_id = 41;
// $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
// $stmt = $conn->prepare("SELECT customer_email FROM memberships where id = '$db_user_id'");
// $stmt->execute();
// // set the resulting array to associative
// $result = $stmt->setFetchMode(PDO::FETCH_ASSOC);
// $customer_get_mail = $stmt->fetchAll()[0]['customer_email'];
// echo $customer_get_mail;
// echo mail("hisham9941@gmail.com","My subject",'hey');


// $fresponse = '{"response":{"paymentStatus":"unpaid","isSuspendedPayment":false,"currency":"EGP","_id":"62f3785ff166b90013a7b998","merchantId":"MID-1902-526","autoGeneratedId":26,"invoiceReferenceId":"44","paymentType":"professional","totalAmount":4666.67,"availableAmountForRefund":4666.67,"description":"some description","state":"submitted","dueDate":"2022-08-10T00:00:00.000Z","invoiceItems":[{"_id":"62f3785ff166b90013a7b999","description":"invoice item description","quantity":1,"itemName":"Membership","unitPrice":4666.67,"subTotal":4666.67}],"customerName":"hishamhassanmahmoud","paymentRequestId":"INV-190252626","tax":0,"creationDate":"2022-08-10T09:20:31.394Z","merchantInfo":{"storeName":"test store name"},"createdByUserId":"5f5ddc068c37cc001f23e55c","transactions":[],"__v":0},"messages":{"en":"Payment request saved","ar":"Payment request saved"},"status":"SUCCESS"}';

// var_dump($fresponse);
// echo '<br><br><br>';
// $result = json_decode($fresponse, false);


// var_dump($result->response->dueDate);




$colors = [

];


// var_dump($colors);
// echo '<br>';
$colors['color4'] = 'blue';
$colors['color5'] = 'black';
// var_dump($colors);
// echo $colors['color3'] . '<br>';
echo $colors['color4'] . '<br>';
echo $colors['color5'] . '<br>';