<?php
require_once('../config.php');

$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://test-api.kashier.io/paymentRequests/MID-1902-526?currency=EGP',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'Authorization: 33ae559e34af351df6ed66b3b714d29d$b6a06d0b28b9c1f1e1c8e5ef774996866f7e55a3782e069a744fb3056ea5ffececb7e402a3c65a98377faa47c6414fb8',
    'Cookie: AWSALB=3RgRfkMcMg2tMdzfQXA2kzm4kH5DijdOeqMq+8XiqNGIgP0VY0zB4xHj1pGr1gAkLroKauHF3FgjhcYkZpiIjWP5laXPt6EzEllX4YdyjPhZCNjwY4yD1aVhkpIp; AWSALBCORS=3RgRfkMcMg2tMdzfQXA2kzm4kH5DijdOeqMq+8XiqNGIgP0VY0zB4xHj1pGr1gAkLroKauHF3FgjhcYkZpiIjWP5laXPt6EzEllX4YdyjPhZCNjwY4yD1aVhkpIp'
  ),
));

$response = curl_exec($curl);

curl_close($curl);

$result = json_decode($response, false);
$last_invoice_id = $result->response->data[0]->autoGeneratedId;



$sql_last_id = $result->response->data[0]->invoiceReferenceId;
$sql_first_id = $last_invoice_id;
$stmt = $conn->prepare("SELECT * FROM memberships WHERE id BETWEEN '$sql_first_id' AND '$sql_last_id'");
$stmt->execute();
$customer_get_mail_sql = $stmt->fetchAll();
// $customer_get_mail_sql[$i]['customer_email']

$kashier_sql_list = [];

foreach($customer_get_mail_sql as $customer_email){
    $kashier_sql_list[$customer_email['kashier_id']] = $customer_email['customer_email'];
}



?>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="../style.css">

    <title>Kashier</title>
</head>
<body>
    <div class="container">
        <table class="container-table">
            <thead>
                <tr>
                    <th class="containerTable-lblTitle">ID</th>
                    <th class="containerTable-lblTitle">Customer Name</th>
                    <th class="containerTable-lblTitle">Customer Email</th>
                    <th class="containerTable-lblTitle">Kashier ID</th>
                    <th class="containerTable-lblTitle">Payment Status</th>
                </tr>
            </thead>
            <tbody class="containerTable-body">
            
            <?php for($i=0; $i<$last_invoice_id; $i++): ?>
                <?php 
                    if($result->response->data[$i]->paymentStatus == 'paid'){
                        echo '<tr class="paid">';
                    }else{
                        echo '<tr>';
                    }
                    ?>
                <td class="containerTable-lblValue">#<?= $result->response->data[$i]->invoiceReferenceId ?></td>
                <td class="containerTable-lblValue"><?= $result->response->data[$i]->customerName ?></td>
                <td class="containerTable-lblValue"><?php if(isset($kashier_sql_list[$result->response->data[$i]->_id])){
                    echo $kashier_sql_list[$result->response->data[$i]->_id];
                }else{
                    echo 'No Data Found';
                }
                 ?></td>
                <td class="containerTable-lblValue"><?php if(isset($result->response->data[$i]->dueDate)){
                 echo date("Y-m-d", strtotime($result->response->data[$i]->dueDate));
                 }else{
                    echo 'No Data Found';
                 } ?></td>
                <td class="containerTable-lblValue"><?= $result->response->data[$i]->paymentStatus ?></td>
                </tr> 
            <?php endfor; ?>
            
            </tbody>
        </table>
    </div>
</body>